version: '3'
services:
  ksi-db:
    image: mysql:8
    container_name: ksi-db
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: desafio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: